# SPDX-FileCopyrightText: 2023 Rivos Inc.
#
# SPDX-License-Identifier: Apache-2.0

[package]
name = "salus"
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = "abort"

[profile.release]
opt-level = "z"
lto = true
strip = "debuginfo"
codegen-units = 1
panic = "abort"

[dependencies]
arrayvec = { version = "0.7.2", default-features = false }
static_assertions = "1.1"
attestation = { path = "./attestation" }
const-oid = { version = "0.9.0", features = ["db"] }
data_model = { path = "./data-model" }
der = "0.7.9"
device_tree = { path = "./device-tree" }
digest = { version = "0.10.7", default-features = false }
drivers = { path = "./drivers" }
ed25519-dalek = { version = "2.1.1", default-features = false }
generic-array = "0.14.5"
hkdf = "0.12.3"
hyp_alloc = { path = "./hyp-alloc" }
memoffset = { version = ">=0.6.5", features = ["unstable_const"] }
mtt = { path = "./mtt" }
page_tracking = { path = "./page-tracking" }
rice = { path = "./rice" }
riscv_page_tables = { path = "./riscv-page-tables" }
riscv_pages = { path = "./riscv-pages" }
riscv_regs = { path = "./riscv-regs" }
s_mode_utils = { path = "./s-mode-utils" }
signature = { version = "2.2.0", default-features = false }
u_mode_api = { path = "./u-mode-api" }
sbi_rs = { path = "./sbi-rs" }
sha2 = { version = "0.10", default-features = false }
sync = { path = "./sync" }
riscv_elf = { path = "./riscv-elf" }
test_system = { path = "./test-system" }

[workspace]

members = ["libuser", "u-mode", "test-workloads"]
