# SPDX-FileCopyrightText: 2025 Rivos Inc.
#
# SPDX-License-Identifier: Apache-2.0

[package]
name = "mtt"
version = "0.1.0"
edition = "2021"

[dependencies]
riscv_pages = { path = "../riscv-pages" }
page_tracking = { path = "../page-tracking" }
sync = { path = "../sync" }
